name: qnow
description: A queue management app for businesses and customers.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  supabase_flutter: ^2.12.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.2.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/qnow_logo.png
